menu title QEMU RISC-V Boot Menu
timeout 20
default linux

label linux
  menu label Boot Buildroot Linux
  kernel /Image
  append root=/dev/vda2 rw rootwait console=ttyS0 earlycon=sbi initcall_debug
  