menu title QEMU ARM64 Boot Menu
timeout 20
default linux

label linux
  menu label Boot Buildroot Linux (AArch64)
  kernel /Image
  append root=/dev/vda2 rw rootwait console=ttyAMA0 initcall_debug
  
  