menu title QEMU ARM64 Boot Menu
timeout 20
default linux

label linux
  menu label Boot Buildroot Linux (AArch64)
  kernel /Image
  append root=/dev/vda2 rw rootwait console=ttyAMA0 initcall_debug m_LFD420_mod_param.use_dma=1 m_LFD420_mod_param.mac_addr=0x00,0x11,0x22,0x33,0x44,0x55
  
  