#!/bin/bash
# ==============================================================================
# MODULE: auto_gdbinit.sh
# DESCRIPTION: Dynamically generates the absolute paths for GDB debugging.
# ==============================================================================


OUTPUT_BASE_DIR=$1
BR2_BUILD_OUTPUT_DIR=$2
HOST_TOOLCHAIN_PREFIX=$3
kernel_version=6.19.8
NEW_VENDOR=buildroot
GDB_AUTO_GDBINIT_FILE="$PROJECT_ROOT/scripts/auto_gdbinit"


VENDORED_TOOLCHAIN_PREFIX=$(echo "$HOST_TOOLCHAIN_PREFIX" | sed -E "s/-[^-]+-/-${NEW_VENDOR}-/")

BR2_SYSROOT="$BR2_BUILD_OUTPUT_DIR/host/${VENDORED_TOOLCHAIN_PREFIX}/sysroot"
BR2_KERNEL_SRC_DIR="$BR2_BUILD_OUTPUT_DIR/build/linux-custom"
KERNEL_SRC_PATH="$KERNEL_SRC_PATH"
DEBUG_TARGET_VMLINUX="$BR2_BUILD_OUTPUT_DIR/build/linux-custom/vmlinux"
DEBUG_TARGET_KMOD_DIR="$BR2_BUILD_OUTPUT_DIR/target/lib/modules/${kernel_version}/updates"

ARCH_GDB_INIT_FILE="$PROJECT_ROOT/scripts/gdb_helper/archsize${ARCH_SIZE}_${ARCH}.gdb"
ARCH_IN_NUMBER=0xFFFF
if [[ "$ARCH" == "riscv" || "$ARCH" == "riscv64" || "$ARCH" == "riscv32" ]]; then
    ARCH_IN_NUMBER=0
elif [[ "$ARCH" == "arm64" || "$ARCH" == "aarch64" || "$ARCH" == "arm"|| "$ARCH" == "arm32"|| "$ARCH" == "aarch32" ]]; then
    ARCH_IN_NUMBER=1
else
    echo ">>> [ERROR] Unsupported architecture: $ARCH"
    exit 1
fi

echo ">>> [INFO] Generating dynamic GDB init script..."

# 4. Write the GDB commands using a Heredoc
# Note: We escape the $ inside the heredoc (\$) so bash prints the literal
# dollar sign for GDB convenience variables, but expands the bash variables.
cat <<EOF > "$GDB_AUTO_GDBINIT_FILE"
# ==============================================================================
# AUTOGENERATED FILE - DO NOT EDIT MANUALLY
# Generated by: scripts/generate_gdbinit.sh
# Target: $TARGET_BOARD | Profile: $BUILD_PROFILE
# ==============================================================================

# 1. Define Convenience Variables
set \$OUTPUT_BASE_DIR = "$OUTPUT_BASE_DIR"
set \$BR2_BUILD_OUTPUT_DIR = "$BR2_BUILD_OUTPUT_DIR"
set \$BR2_SYSROOT = "$BR2_SYSROOT"
set \$BR2_KERNEL_SRC_DIR = "$BR2_KERNEL_SRC_DIR"
set \$KERNEL_SRC_PATH = "$KERNEL_SRC_PATH"
set \$DEBUG_TARGET_VMLINUX = "$DEBUG_TARGET_VMLINUX"
set \$DEBUG_TARGET_KMOD_DIR = "$DEBUG_TARGET_KMOD_DIR"

set \$TARGET_BOARD = "$TARGET_BOARD"
set \$BUILD_PROFILE = "$BUILD_PROFILE"
set \$build_ARCH = "$ARCH"
set \$build_ARCH_SIZE = "$ARCH_SIZE"
set \$build_CROSS_COMPILE = "$CROSS_COMPILE"
set \$TARGET_BR2_DEFCONFIG = "$TARGET_BR2_DEFCONFIG"
set \$PROJECT_ROOT="$PROJECT_ROOT"
set \$ARCH_IN_NUMBER = $ARCH_IN_NUMBER

set sysroot $BR2_SYSROOT
directory $BR2_KERNEL_SRC_DIR

add-auto-load-safe-path $OUTPUT_BASE_DIR
add-auto-load-safe-path $BR2_KERNEL_SRC_DIR


printf ">>> [AUTO] GDB Sysroot set to: %s\n", \$BR2_SYSROOT
printf ">>> [AUTO] GDB Source Directory added: %s\n", \$BR2_KERNEL_SRC_DIR

show sysroot
show directories

source $ARCH_GDB_INIT_FILE
EOF

echo ">>> [SUCCESS] GDB setup written to: $GDB_AUTO_GDBINIT_FILE"